version: '3.1'

services:
  mail:
    build:
      context: ./mailhog
      dockerfile: Dockerfile
    container_name: mailhog
    ports:
      - "8025:8025"
    depends_on:
      - mongo
    environment: # see https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md
      MH_MAILDIR_PATH: /tmp
      MH_STORAGE: mongodb
      MH_MONGO_COLLECTION: messages
      MH_MONGO_DB: mailhog
      MH_MONGO_URI: mongodb://mongo:27017
    networks:
      - br0
    volumes:
      - maildir:/tmp
      - "./bin/mhsendmail:/usr/local/bin/mhsendmail"


  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-volume:/data/db


volumes:
  db-volume:
  maildir: {}

networks:
  br0:
    driver: bridge